debug: false
smsEnabled: false
rpc:
    listen: "0.0.0.0:1986"
web: 
    addrs: 
      - "127.0.0.1:1985"
    timeout: 300 
    interval: 60 #get strategy interval
smtp: 
    enabled: false
    addr: "mail.addr:25"
    username: "mail@mail.com"
    password: ""
    from: "mail@mail.com"
wechat:
    enabled: false
    toparty: "@all"     #需要发送指定人请使用"@all"
    agentid: 1000008
    corpid: ""
    corpsecret: ""
worker: 
    sms: 10  #send sms concurrency
    mail: 50 #send mail concurrency
    wechat: 50  #send wechat concurrency
# remain: 30
